version: '3.4'

services:
    catalogodb:
        container_name: catalogodb
        restart: always
        ports:
            - "27017:27107"
        volumes:
            - mongo_data:/data/db

    catalogo.api:
        container_name: catalogo.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalogodb:27017"
        depends_on:
            - catalogodb
        ports:
            - '8000:80'
